[package]
name = "andyleung9527_demo_crates"
version = "0.1.0"
edition = "2021"
description = "A demo crate."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
